#!/bin/bash

if [ -t 1 ]; then
    podman run --interactive --tty --rm -v $(pwd):/usr/src/myapp -w /usr/src/myapp --network host docker.io/library/php php "$@"
else
    podman run --rm -v $(pwd):/usr/src/myapp -w /usr/src/myapp --network host docker.io/library/php php "$@"
fi
