#!/bin/bash

if [ -t 1 ]; then
    podman run --interactive --tty --rm -v $(pwd):/var/www/html --network host localhost/php8.2:latest php "$@"
else
    podman run --rm -v $(pwd):/var/www/html --network host localhost/php8.2:latest php "$@"
fi
