[window]
decorations = 'None'
[font]
size = 14
[font.normal]
family = "CaskaydiaMono Nerd Font Propo"
[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\uE002"
# Useful for Windows
# [[keyboard.bindings]]
# key = "Space"
# mods = "Control"
# chars = "\u0000"
